import json
import sys
from bs4 import BeautifulSoup

def generate_html_index(json_data):
	html_str = """<html lang="en">
<head>
    <!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-W3PN4DNT');</script>
	<!-- End Google Tag Manager -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Cache-Control" content="no-cache">
	
	<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7361580094970368" crossorigin="anonymous"></script>
    <title>AI Blog</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
	<!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W3PN4DNT"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->
    <header>
		<h1>Welcome to the AI-Powered Blog: Where Technology Takes the Lead in Storytelling</h1>
<p>In recent years, artificial intelligence has made incredible strides, reshaping industries, redefining creativity, and even expanding our understanding of what it means to generate original content. From chatbots and language models that can hold conversations to image generators that create breathtaking visuals from scratch, AI is becoming a creative force in its own right. This blog exists at the intersection of these advancements, using cutting-edge AI to select topics and craft each article you'll find here.</p>
<br><p>Every piece on this blog represents the work of an AI model capable of processing vast amounts of information, synthesizing trends, and spotting topics that people are likely curious about - before they even know it themselves. By analyzing trends, news stories, and emerging discussions, the AI picks subjects that are timely, intriguing, and relevant. This isn't just automation; it's an AI-driven discovery process that evolves with each article, each topic choice, and each advancement in machine learning.</p>
<br><p>The articles themselves are then generated by sophisticated language models, trained on millions of words from a diverse range of sources. These models can write with fluency, explain complex ideas simply, and even infuse a bit of style and personality. The process of AI creation doesn't just end with typing up words, though. The AI evaluates tone, clarity, and coherence, ensuring that every post meets the standards you'd expect from a human writer, with an added layer of objectivity and unbiased perspective.</p>
<br><p>What makes this blog truly special is that it offers a glimpse into the creative capabilities of AI, challenging the traditional boundaries between human and machine. By reading these articles, you're exploring a new kind of journalism and storytelling. Each post is a product of thousands of calculations, data analyses, and algorithms coming together to mimic human creativity - and, in many cases, match it.</p>
<br><p>Whether you're a tech enthusiast, curious reader, or AI skeptic, this blog is a space to witness the potential of AI in content creation. So dive into topics that have been meticulously chosen and crafted by the latest technology. You might be surprised by what AI has to say!</p>
        <button id="theme-toggle">Toggle Theme</button>
    </header>

    <main id="article-list">
        <section>
		"""

	for topic_data in json_data:
		topic = topic_data['topic']
		subtopics = topic_data['subtopics']

		html_str += f"""<details>
				<summary><a href="{topic.replace(' ', '_')}.html">{topic}</a></summary>
				<ul>
				"""

		for subtopic in subtopics:
			html_str += f"""<li><a href="{topic.replace(' ', '_')}_-_{subtopic.replace(' ', '_')}.html">{subtopic}</a></li>
			"""

		html_str += """</ul>
			</details>
		"""

	html_str += """
        </section>
    </main>

    <footer>
        <p>© 2024 AI Blog. All rights reserved.</p>
    </footer>

    <script type=text/javascript src="scripts/scripts.js"></script>
</body>
</html>
	"""
	html_str = BeautifulSoup(html_str, 'html.parser').prettify()
	with open('index.html', 'w') as f:
		f.write("<!DOCTYPE html>\n")
		f.write(html_str)

def main(topicFile):
	# Load the JSON data
	with open(topicFile, 'r') as f:
		data = json.load(f)

	# Generate the HTML index
	generate_html_index(data)

if __name__ == "__main__":
	main(sys.argv[1])